#etna
services:
  etna:
    #image: etna:latest
    build: .
    container_name: etna
    hostname: etna
    restart: unless-stopped
    environment:
      TZ: Europe/Paris
    volumes:
      - ./settings:/app/settings:ro
      - /shares/nuwa_saved:/shares/nuwa_saved
      - /shares/etna_share:/shares/etna_share
      - /shares/nuwa_stabilized:/shares/nuwa_stabilized
      - ./tmp_folder:/tmp/etna/tmp
      - ./output_folder:/tmp/etna
    ports:
      - 36100:36100/tcp
    networks:
      - spacebro
      - default

networks:
  default:
  spacebro:
    external: true