#etna
services:
  etna-melt:
    #image: etna:latest
    build: .
    container_name: etna-melt
    hostname: etna-melt
    restart: unless-stopped
    environment:
      TZ: Europe/Paris
    volumes:
      - ./settings:/app/settings:ro
      - ./tmp_folder:/tmp/etna/tmp
      - ./output_folder:/tmp/etna
    ports:
      - 36101:36101/tcp
    networks:
      - spacebro
      - default

networks:
  default:
  spacebro:
    external: true